use super::AspectCluster;

#[allow(clippy::too_many_lines)]
pub fn noun_pool(archetype: &str, cluster: AspectCluster) -> &'static [&'static str] {
    match (archetype, cluster) {
        ("Weapon", AspectCluster::Physical) => &[
            "Blade", "Maul", "Cleaver", "Hammer", "Edge", "Bludgeon", "Pike", "Flail", "Glaive",
            "Hatchet", "Mace", "Scourge",
        ],
        ("Weapon", AspectCluster::Elemental) => &[
            "Brand",
            "Frostfang",
            "Sunblade",
            "Ashbringer",
            "Ember",
            "Shard",
            "Cindercore",
            "Stormtooth",
            "Glacieredge",
            "Inferno",
            "Duskfang",
            "Thunderbite",
        ],
        ("Weapon", AspectCluster::Nature) => &[
            "Thorn",
            "Briar",
            "Rootcleaver",
            "Fang",
            "Stinger",
            "Husk",
            "Talon",
            "Quill",
            "Barb",
            "Claw",
            "Mandible",
            "Spine",
        ],
        ("Weapon", AspectCluster::Arcane) => &[
            "Voidedge",
            "Riftblade",
            "Phasecutter",
            "Flux",
            "Shiftshard",
            "Warp",
            "Nullblade",
            "Driftfang",
            "Banelight",
            "Fracture",
            "Schism",
            "Severance",
        ],

        ("Shield", AspectCluster::Physical) => &[
            "Bulwark", "Plate", "Rampart", "Guard", "Wall", "Bastion", "Buckler", "Aegis",
            "Fortress", "Barrier", "Parapet", "Redoubt",
        ],
        ("Shield", AspectCluster::Elemental) => &[
            "Aegis",
            "Flameward",
            "Frostguard",
            "Dawnshield",
            "Veil",
            "Mantle",
            "Stormwall",
            "Embershield",
            "Haloguard",
            "Cinderplate",
            "Glacierwall",
            "Duskmantle",
        ],
        ("Shield", AspectCluster::Nature) => &[
            "Barkwall",
            "Thornguard",
            "Rootbulwark",
            "Huskshield",
            "Shell",
            "Carapace",
            "Chitin",
            "Coralplate",
            "Ironbark",
            "Petrified",
            "Scalewall",
            "Rindguard",
        ],
        ("Shield", AspectCluster::Arcane) => &[
            "Voidwall",
            "Phaseguard",
            "Riftbarrier",
            "Warpshield",
            "Nexus",
            "Ward",
            "Nullward",
            "Driftshield",
            "Baneguard",
            "Aegisrift",
            "Lattice",
            "Oubliette",
        ],

        ("Spell", AspectCluster::Physical) => &[
            "Shatter",
            "Crush",
            "Tremor",
            "Quake",
            "Impact",
            "Shockwave",
            "Rupture",
            "Fracture",
            "Avalanche",
            "Rend",
            "Pummel",
            "Concussion",
        ],
        ("Spell", AspectCluster::Elemental) => &[
            "Bolt",
            "Flare",
            "Frostbolt",
            "Pyre",
            "Sunburst",
            "Eclipse",
            "Tempest",
            "Conflagrate",
            "Hailstorm",
            "Corona",
            "Discharge",
            "Ignition",
        ],
        ("Spell", AspectCluster::Nature) => &[
            "Bloom",
            "Blight",
            "Overgrowth",
            "Wilt",
            "Tangle",
            "Rootgrasp",
            "Sporeling",
            "Canker",
            "Engulf",
            "Miasma",
            "Constrict",
            "Putrefy",
        ],
        ("Spell", AspectCluster::Arcane) => &[
            "Rift",
            "Voidbolt",
            "Warpweave",
            "Phaseshift",
            "Paradox",
            "Flux",
            "Unraveling",
            "Annulment",
            "Singularity",
            "Displacement",
            "Inversion",
            "Collapse",
        ],

        ("Healer", AspectCluster::Physical) => &[
            "Salve",
            "Balm",
            "Poultice",
            "Compress",
            "Splint",
            "Bandage",
            "Suture",
            "Tincture",
            "Tourniquet",
            "Liniment",
            "Draught",
            "Plaster",
        ],
        ("Healer", AspectCluster::Elemental) => &[
            "Elixir",
            "Sunwater",
            "Frostbalm",
            "Embertonic",
            "Radiance",
            "Glow",
            "Dawnlight",
            "Solace",
            "Glimmer",
            "Balmfire",
            "Warmth",
            "Luminance",
        ],
        ("Healer", AspectCluster::Nature) => &[
            "Bloom", "Remedy", "Verdance", "Sprout", "Renewal", "Sap", "Nectar", "Salve",
            "Dewdrop", "Regrowth", "Pollen", "Chloris",
        ],
        ("Healer", AspectCluster::Arcane) => &[
            "Mend",
            "Restoration",
            "Phaseweave",
            "Paradox",
            "Flux",
            "Reversal",
            "Restitution",
            "Reconvergence",
            "Rethread",
            "Stasis",
            "Continuum",
            "Recursion",
        ],

        ("Scout", AspectCluster::Physical) => &[
            "Stride", "Footing", "Bearing", "Passage", "Track", "March", "Venture", "Sprint",
            "Traverse", "Ranging", "Advance", "Waypoint",
        ],
        ("Scout", AspectCluster::Elemental) => &[
            "Flicker",
            "Glint",
            "Frostpath",
            "Embertrace",
            "Signal",
            "Gleam",
            "Flashpoint",
            "Beacon",
            "Shimmer",
            "Aurora",
            "Sparktrail",
            "Mirage",
        ],
        ("Scout", AspectCluster::Nature) => &[
            "Trail",
            "Scent",
            "Trace",
            "Omen",
            "Burrow",
            "Path",
            "Forage",
            "Spoor",
            "Thicket",
            "Undergrowth",
            "Slink",
            "Prowl",
        ],
        ("Scout", AspectCluster::Arcane) => &[
            "Vantage",
            "Rift",
            "Warp",
            "Phase",
            "Blink",
            "Vista",
            "Farsight",
            "Breach",
            "Aperture",
            "Translocation",
            "Scrye",
            "Glimpse",
        ],

        ("Artifact", AspectCluster::Physical) => &[
            "Relic", "Totem", "Idol", "Slab", "Monolith", "Anvil", "Obelisk", "Crucible",
            "Keystone", "Sigil", "Pillar", "Stele",
        ],
        ("Artifact", AspectCluster::Elemental) => &[
            "Orb",
            "Prism",
            "Lantern",
            "Censer",
            "Brazier",
            "Crystal",
            "Phylactery",
            "Crucible",
            "Thurible",
            "Chandelier",
            "Lodestone",
            "Vessel",
        ],
        ("Artifact", AspectCluster::Nature) => &[
            "Seedstone",
            "Root",
            "Fossil",
            "Husk",
            "Acorn",
            "Heartwood",
            "Petrified",
            "Amber",
            "Coprolite",
            "Cairn",
            "Geode",
            "Lignite",
        ],
        ("Artifact", AspectCluster::Arcane) => &[
            "Focus",
            "Catalyst",
            "Nexus",
            "Gate",
            "Lens",
            "Conduit",
            "Orrery",
            "Tesseract",
            "Reliquary",
            "Astrolabe",
            "Talisman",
            "Fulcrum",
        ],

        // Fallback for unknown archetypes
        (_, AspectCluster::Physical) => &[
            "Fragment", "Shard", "Remnant", "Chunk", "Scrap", "Sliver", "Splinter", "Morsel",
            "Dregs", "Ruin", "Wreckage", "Debris",
        ],
        (_, AspectCluster::Elemental) => &[
            "Spark", "Ember", "Wisp", "Mote", "Gleam", "Flicker", "Cinder", "Fume", "Vapour",
            "Plume", "Glint", "Smoulder",
        ],
        (_, AspectCluster::Nature) => &[
            "Spore", "Root", "Seed", "Husk", "Twig", "Petal", "Frond", "Tendril", "Lichen",
            "Fungus", "Burr", "Moss",
        ],
        (_, AspectCluster::Arcane) => &[
            "Echo",
            "Vestige",
            "Trace",
            "Rift",
            "Ripple",
            "Anomaly",
            "Remnant",
            "Glitch",
            "Cipher",
            "Sigil",
            "Enigma",
            "Distortion",
        ],
    }
}
