use std::fmt::Write;

use engine_render::prelude::PathCommand;
use terrain::prelude::{
    AnnotatedShape, GameplayTag, ShapePurpose, TerrainTileDefinition, TerrainTileSet, TilePattern,
    TileVariant,
};

/// Generate a complete Rust source file that returns a `TerrainTileSet`.
///
/// Output is a self-contained `.rs` file with imports, one public entry function,
/// and one private function per terrain type. Floats are rounded to 2 decimal places.
pub fn generate_tileset_code(
    tileset: &TerrainTileSet,
    fn_name: &str,
    tsx_filename: &str,
) -> String {
    let mut out = String::new();

    // Header
    let _ = writeln!(out, "// Generated by tiled-to-shapes from {tsx_filename}");
    let _ = writeln!(out, "// Do not edit manually.");
    out.push('\n');

    // Imports
    out.push_str("use std::collections::BTreeMap;\n");
    out.push_str("use engine_render::prelude::PathCommand;\n");
    out.push_str("use glam::Vec2;\n");
    out.push_str("use terrain::prelude::*;\n");
    out.push('\n');

    // Top-level function
    let _ = writeln!(out, "pub fn {fn_name}() -> TerrainTileSet {{");
    let _ = writeln!(out, "    TerrainTileSet {{");
    let _ = writeln!(out, "        tiles: BTreeMap::from([");
    for name in tileset.tiles.keys() {
        let safe_id = safe_fn_name(name);
        let _ = writeln!(out, "            (\"{name}\".to_owned(), {safe_id}()),");
    }
    let _ = writeln!(out, "        ]),");
    let _ = writeln!(out, "        adjacency_rules: Vec::new(),");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    out.push('\n');

    // Per-terrain-type functions
    for (name, def) in &tileset.tiles {
        write_terrain_fn(&mut out, name, def);
        out.push('\n');
    }

    out
}

fn write_terrain_fn(out: &mut String, name: &str, def: &TerrainTileDefinition) {
    let safe_id = safe_fn_name(name);
    let _ = writeln!(out, "fn {safe_id}() -> TerrainTileDefinition {{");
    let _ = writeln!(out, "    TerrainTileDefinition {{");
    let _ = writeln!(out, "        name: \"{name}\".to_owned(),");
    let _ = writeln!(out, "        variants: [");
    for variant in &def.variants {
        write_variant(out, name, variant);
        out.push_str(",\n");
    }
    let _ = writeln!(out, "        ],");
    let _ = writeln!(out, "        priority: {},", def.priority);
    let _ = writeln!(
        out,
        "        tint_range: TintRange {{ hue_shift_max: {}, brightness_shift_max: {} }},",
        fmt_f32(def.tint_range.hue_shift_max),
        fmt_f32(def.tint_range.brightness_shift_max)
    );
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
}

fn write_variant(out: &mut String, terrain_name: &str, variant: &TileVariant) {
    let pattern_str = match variant.pattern {
        TilePattern::Solid => "TilePattern::Solid",
        TilePattern::OuterCorner => "TilePattern::OuterCorner",
        TilePattern::Edge => "TilePattern::Edge",
        TilePattern::Diagonal => "TilePattern::Diagonal",
        TilePattern::InnerCorner => "TilePattern::InnerCorner",
    };
    out.push_str("            TileVariant {\n");
    let _ = writeln!(out, "                pattern: {pattern_str},");
    out.push_str("                shapes: vec![\n");
    for shape in &variant.shapes {
        write_annotated_shape(out, shape, terrain_name);
        out.push_str(",\n");
    }
    out.push_str("                ],\n");
    out.push_str("                edge_ids: [EdgeId::NONE; 4],\n");
    out.push_str("            }");
}

fn write_annotated_shape(out: &mut String, shape: &AnnotatedShape, terrain_name: &str) {
    let purpose_str = match shape.purpose {
        ShapePurpose::Fill => "ShapePurpose::Fill",
        ShapePurpose::Boundary => "ShapePurpose::Boundary",
        ShapePurpose::Decoration => "ShapePurpose::Decoration",
    };
    let tags_str = format_gameplay_tags(&shape.gameplay_tags);
    let terrain_tag = &shape.terrain_tag;
    // Use provided terrain_tag, fall back to name
    let tag = if terrain_tag.is_empty() {
        terrain_name
    } else {
        terrain_tag.as_str()
    };

    out.push_str("                    AnnotatedShape {\n");
    out.push_str("                        path: vec![\n");
    for cmd in &shape.path {
        out.push_str("                            ");
        write_path_command(out, cmd);
        out.push_str(",\n");
    }
    out.push_str("                        ],\n");
    let [r, g, b, a] = shape.color;
    let _ = writeln!(
        out,
        "                        color: [{}, {}, {}, {}],",
        fmt_f32(r),
        fmt_f32(g),
        fmt_f32(b),
        fmt_f32(a)
    );
    let _ = writeln!(
        out,
        "                        terrain_tag: \"{tag}\".to_owned(),"
    );
    let _ = writeln!(out, "                        purpose: {purpose_str},");
    let _ = writeln!(out, "                        gameplay_tags: {tags_str},");
    out.push_str("                    }");
}

fn write_path_command(out: &mut String, cmd: &PathCommand) {
    match cmd {
        PathCommand::MoveTo(v) => {
            let _ = write!(
                out,
                "PathCommand::MoveTo(Vec2::new({}, {}))",
                fmt_f32(v.x),
                fmt_f32(v.y)
            );
        }
        PathCommand::LineTo(v) => {
            let _ = write!(
                out,
                "PathCommand::LineTo(Vec2::new({}, {}))",
                fmt_f32(v.x),
                fmt_f32(v.y)
            );
        }
        PathCommand::QuadraticTo { control, to } => {
            let _ = write!(
                out,
                "PathCommand::QuadraticTo {{ control: Vec2::new({}, {}), to: Vec2::new({}, {}) }}",
                fmt_f32(control.x),
                fmt_f32(control.y),
                fmt_f32(to.x),
                fmt_f32(to.y)
            );
        }
        PathCommand::CubicTo {
            control1,
            control2,
            to,
        } => {
            let _ = write!(
                out,
                "PathCommand::CubicTo {{ control1: Vec2::new({}, {}), control2: Vec2::new({}, {}), to: Vec2::new({}, {}) }}",
                fmt_f32(control1.x),
                fmt_f32(control1.y),
                fmt_f32(control2.x),
                fmt_f32(control2.y),
                fmt_f32(to.x),
                fmt_f32(to.y)
            );
        }
        PathCommand::Close => out.push_str("PathCommand::Close"),
        PathCommand::Reverse => out.push_str("PathCommand::Reverse"),
    }
}

fn format_gameplay_tags(tags: &[GameplayTag]) -> String {
    if tags.is_empty() {
        return "vec![]".to_owned();
    }
    let items: Vec<&str> = tags
        .iter()
        .map(|t| match t {
            GameplayTag::Solid => "GameplayTag::Solid",
            GameplayTag::HurtsPlayer => "GameplayTag::HurtsPlayer",
            GameplayTag::DifficultTerrain => "GameplayTag::DifficultTerrain",
            GameplayTag::BlocksVision => "GameplayTag::BlocksVision",
        })
        .collect();
    format!("vec![{}]", items.join(", "))
}

/// Round float to 2 decimal places for codegen output.
fn fmt_f32(v: f32) -> String {
    let rounded = (v * 100.0).round() / 100.0;
    let r = if rounded == 0.0 && rounded.is_sign_negative() {
        0.0_f32
    } else {
        rounded
    };
    let s = format!("{r}");
    if s.contains('.') { s } else { format!("{r}.0") }
}

/// Convert a name to a valid Rust function name (`snake_case`, no hyphens).
fn safe_fn_name(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect::<String>()
        .to_ascii_lowercase()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;
    use terrain::prelude::{
        EdgeId, TerrainTileDefinition, TerrainTileSet, TilePattern, TileVariant, TintRange,
    };

    fn empty_tileset(fn_name_key: &str) -> TerrainTileSet {
        let def = TerrainTileDefinition {
            name: fn_name_key.to_owned(),
            variants: [
                TileVariant {
                    pattern: TilePattern::Solid,
                    shapes: vec![],
                    edge_ids: [EdgeId::NONE; 4],
                },
                TileVariant {
                    pattern: TilePattern::OuterCorner,
                    shapes: vec![],
                    edge_ids: [EdgeId::NONE; 4],
                },
                TileVariant {
                    pattern: TilePattern::Edge,
                    shapes: vec![],
                    edge_ids: [EdgeId::NONE; 4],
                },
                TileVariant {
                    pattern: TilePattern::Diagonal,
                    shapes: vec![],
                    edge_ids: [EdgeId::NONE; 4],
                },
                TileVariant {
                    pattern: TilePattern::InnerCorner,
                    shapes: vec![],
                    edge_ids: [EdgeId::NONE; 4],
                },
            ],
            priority: 0,
            tint_range: TintRange {
                hue_shift_max: 5.0,
                brightness_shift_max: 0.05,
            },
        };
        TerrainTileSet {
            tiles: BTreeMap::from([(fn_name_key.to_owned(), def)]),
            adjacency_rules: Vec::new(),
        }
    }

    #[test]
    fn when_generate_then_contains_pub_fn_tileset() {
        // Arrange
        let tileset = empty_tileset("grass");
        // Act
        let code = generate_tileset_code(&tileset, "tileset", "terrain.tsx");
        // Assert
        assert!(
            code.contains("pub fn tileset()"),
            "missing pub fn tileset()"
        );
    }

    #[test]
    fn when_generate_then_contains_terrain_tileset_constructor() {
        let tileset = empty_tileset("grass");
        let code = generate_tileset_code(&tileset, "tileset", "terrain.tsx");
        assert!(code.contains("TerrainTileSet"), "missing TerrainTileSet");
    }

    #[test]
    fn when_generate_then_contains_terrain_prelude_import() {
        let tileset = empty_tileset("grass");
        let code = generate_tileset_code(&tileset, "tileset", "terrain.tsx");
        assert!(
            code.contains("use terrain::prelude::*"),
            "missing terrain prelude import"
        );
    }

    #[test]
    fn when_custom_fn_name_then_uses_it() {
        let tileset = empty_tileset("grass");
        let code = generate_tileset_code(&tileset, "my_tileset", "terrain.tsx");
        assert!(
            code.contains("pub fn my_tileset()"),
            "missing custom fn name"
        );
    }
}
