use std::path::{Path, PathBuf};

use tiled_to_shapes::pipeline::{default_convert_config, generate_build_code};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=assets/terrain");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = PathBuf::from(&out_dir).join("terrain.rs");

    let assets_dir = Path::new("assets/terrain");

    // Collect TSX files
    let tsx_paths: Vec<PathBuf> = if assets_dir.is_dir() {
        std::fs::read_dir(assets_dir)
            .into_iter()
            .flatten()
            .flatten()
            .filter(|e| {
                e.path()
                    .extension()
                    .is_some_and(|ext| ext.eq_ignore_ascii_case("tsx"))
            })
            .map(|e| e.path())
            .collect()
    } else {
        Vec::new()
    };

    // Emit rerun-if-changed for each TSX and its adjacent PNG
    for tsx in &tsx_paths {
        println!("cargo:rerun-if-changed={}", tsx.display());
        if let Ok(xml) = std::fs::read_to_string(tsx)
            && let Some(src) = extract_image_source(&xml)
        {
            let png = tsx.parent().unwrap_or(Path::new(".")).join(src);
            println!("cargo:rerun-if-changed={}", png.display());
        }
    }

    if tsx_paths.is_empty() {
        println!(
            "cargo:warning=tiled-to-shapes: no TSX files in assets/terrain/ \
             — generated tileset is empty. Add TSX + PNG tilesheet pairs to populate."
        );
        write_empty_stub(&out_path);
        return;
    }

    let refs: Vec<&Path> = tsx_paths.iter().map(PathBuf::as_path).collect();
    let config = default_convert_config();
    let (code, warnings) = generate_build_code(&refs, &config);

    for (path, err) in warnings {
        println!("cargo:warning=tiled-to-shapes: skipping {path}: {err}");
    }

    std::fs::write(&out_path, code).expect("failed to write terrain.rs");
}

fn write_empty_stub(out_path: &Path) {
    let stub = "\
// Generated by card_game build.rs — no TSX assets found in assets/terrain/.
// Add TSX + PNG tilesheet pairs to assets/terrain/ and rebuild to populate.

use std::collections::BTreeMap;
use terrain::prelude::TerrainTileSet;

/// Returns an empty `TerrainTileSet`. Populated once TSX assets are added.
pub fn tileset() -> TerrainTileSet {
    TerrainTileSet {
        tiles: BTreeMap::new(),
        adjacency_rules: Vec::new(),
    }
}
";
    std::fs::write(out_path, stub).expect("failed to write stub terrain.rs");
}

/// Extract `source` attribute value from `<image source="...">` in TSX XML.
fn extract_image_source(xml: &str) -> Option<&str> {
    let tag_start = xml.find("<image ")?;
    let tag = &xml[tag_start..];
    let src_start = tag.find("source=\"")? + "source=\"".len();
    let src_end = tag[src_start..].find('"')? + src_start;
    Some(&tag[src_start..src_end])
}
