[package]
name = "card_game_bin"
edition.workspace = true
version.workspace = true

[features]
ui-test = []

[lints]
workspace = true

[dependencies]
axiom2d = { path = "../axiom2d" }
bevy_ecs = { workspace = true }
card_game = { path = "../card_game" }
engine_render = { path = "../engine_render" }
glam = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
tracing-subscriber = { workspace = true }
