//! Shared hydration functions for compact generated shape data.
//!
//! Auto-generated by img-to-shape — do not edit by hand.

use engine_core::color::Color;
use engine_render::shape::{PathCommand, Shape, ShapeVariant};
use glam::Vec2;

const SHARED_PALETTE: &[u8] = &[
    227, 12, 33, 10, 76, 132, 211, 88, 246, 101, 72, 36, 247, 231, 105, 84,
    160, 243, 4, 236, 66, 214, 216, 212, 159, 158, 145, 93, 41, 176, 217, 140,
    12, 9, 126, 14, 24, 12, 6, 73, 179, 78, 242, 127, 113, 5, 214, 228,
    11, 71, 48, 137, 227, 133, 155, 54, 10, 86, 56, 88, 168, 161, 49, 161,
    59, 197, 11, 178, 154, 139, 238, 246, 249, 170, 172, 34, 79, 237, 244, 55,
    105, 119, 138, 7, 139, 14, 239, 241, 88, 42, 119, 113, 104, 152, 153, 221,
    201, 215, 18, 198, 186, 142, 98, 98, 184, 10, 159, 240, 94, 9, 7, 188,
    98, 75, 129, 220, 28, 239, 172, 86, 50, 106, 91, 122, 71, 239, 158, 4,
    117, 57, 176, 11, 208, 6, 250, 190, 241, 197, 246, 232, 183, 75, 237, 247,
    57, 20, 49, 219, 168, 238, 184, 90, 12, 16, 120, 185, 229, 184, 140, 117,
    194, 120, 1, 3, 185, 67, 228, 84, 133, 88, 149, 246, 247, 245, 161, 189,
    17, 61, 181, 198, 58, 98, 19, 242, 134, 68, 136, 199, 204, 10, 57, 92,
    177, 224, 97, 180, 122, 202, 45, 77, 168, 8, 170, 31, 130, 16, 161, 9,
    135, 116, 80, 142, 174, 54, 142, 215, 242, 54, 15, 250, 197, 22, 196, 51,
    46, 121, 178, 235, 198, 44, 170, 123, 69, 47, 166, 203, 231, 208, 238, 247,
    196, 185, 174, 83, 86, 144, 168, 135, 101, 80, 142, 122, 44, 64, 7, 75,
    25, 108, 136, 8, 11, 220, 161, 48, 127, 155, 33, 240, 107, 137, 144, 87,
    23, 126, 91, 57, 241, 27, 62, 157, 10, 200, 213, 165, 161, 236, 241, 139,
    119, 148, 172, 236, 203, 193, 152, 137, 165, 19, 91, 18, 249, 229, 66, 85,
    107, 9, 76, 18, 158, 93, 85, 76, 12, 196, 187, 96, 46, 18, 72, 225,
    182, 20, 118, 228, 27, 40, 161, 57, 122, 158, 199, 11, 10, 244, 203, 240,
    70, 38, 18, 75, 41, 241, 52, 140, 64, 124, 139, 230, 17, 71, 190, 61,
    207, 238, 12, 88, 71, 245, 199, 117, 124, 128, 141, 136, 200, 65, 235, 96,
    94, 190, 158, 124, 35, 106, 42, 157, 60, 243, 186, 83, 185, 10, 27, 30,
    24, 165, 68, 168, 100, 238, 238, 116, 244, 196, 6, 148, 186, 121, 19, 227,
    232, 227, 107, 22, 133, 204, 99, 224, 107, 219, 104, 49, 114, 201, 98, 171,
    196, 63, 62, 61, 123, 185, 155, 87, 201, 242, 189, 30, 222, 168, 18, 76,
    65, 108, 234, 210, 185, 69, 61, 135, 28, 168, 49, 127, 144, 233, 166, 117,
    8, 199, 119, 183, 29, 32, 21, 119, 243, 148, 142, 101, 59, 121, 229, 70,
    201, 57, 28, 84, 38, 154, 194, 85, 163, 36, 244, 222, 9, 250, 240, 212,
    18, 102, 153, 245, 169, 239, 164, 95, 49, 133, 21, 86, 105, 44, 221, 173,
    124, 70, 197, 198, 215, 86, 54, 45, 154, 39, 39, 17, 212, 64, 219, 103,
    13, 126, 62, 198, 122, 31, 18, 223, 172, 113, 220, 23, 190, 88, 230, 122,
    62, 202, 156, 202, 152, 85, 234, 18, 9, 50, 22, 9, 244, 180, 48, 100,
    171, 97, 71, 178, 224, 178, 223, 47, 149, 112, 45, 96, 118, 42, 146, 38,
    202, 173, 182, 201, 118, 69, 19, 197, 212, 242, 121, 62, 142, 53, 74, 120,
    187, 101, 116, 84, 65, 15, 52, 70, 89, 103, 234, 244, 185, 73, 211, 201,
    128, 54, 240, 132, 25, 165, 224, 196, 50, 23, 205, 221, 70, 72, 200, 206,
    190, 231, 207, 165, 8, 152, 211, 10, 60, 239, 166, 181, 103, 196, 138, 229,
    50, 176, 125, 169, 11, 17, 131, 205, 238, 89, 215, 26, 92, 118, 139, 71,
    139, 91, 105, 155, 142, 43, 47, 43, 32, 246, 90, 161, 202, 160, 10, 117,
    90, 30, 215, 190, 154, 92, 178, 33, 133, 39, 42, 168, 226, 144, 111, 79,
    128, 147, 74, 101, 20, 57, 45, 87, 199, 192, 53, 11, 196, 42, 78, 133,
    124, 195, 248, 216, 143, 16, 146, 161, 139, 46, 167, 220, 114, 199, 48, 193,
    47, 232, 145, 218, 218, 58, 241, 11, 49, 21, 29, 237, 246, 18, 33, 71,
    242, 165, 7, 146, 139, 121, 1, 194, 1, 199, 131, 95, 170, 180, 238, 164,
    167, 174, 171, 232, 246, 248, 15, 231, 151, 73, 67, 130, 171, 194, 88, 96,
    104, 175, 10, 250, 94, 129, 208, 241, 203, 79, 60, 104, 124, 209, 239, 70,
];

pub fn hydrate_shapes(data: &[f32]) -> Vec<Shape> {
    let mut shapes = Vec::new();
    let mut i = 0;
    while i < data.len() {
        let tag = data[i] as u8;
        i += 1;
        if tag == 4 {
            let color = Color::new(data[i], data[i + 1], data[i + 2], data[i + 3]);
            i += 4;
            let mut commands = Vec::new();
            while i < data.len() && data[i] as u8 != 4 {
                let cmd_tag = data[i] as u8;
                i += 1;
                match cmd_tag {
                    0 => {
                        commands.push(PathCommand::MoveTo(Vec2::new(data[i], data[i + 1])));
                        i += 2;
                    }
                    1 => {
                        commands.push(PathCommand::LineTo(Vec2::new(data[i], data[i + 1])));
                        i += 2;
                    }
                    2 => {
                        commands.push(PathCommand::CubicTo {
                            control1: Vec2::new(data[i], data[i + 1]),
                            control2: Vec2::new(data[i + 2], data[i + 3]),
                            to: Vec2::new(data[i + 4], data[i + 5]),
                        });
                        i += 6;
                    }
                    3 => {
                        commands.push(PathCommand::Close);
                    }
                    _ => break,
                }
            }
            shapes.push(Shape {
                variant: ShapeVariant::Path { commands },
                color,
            });
        }
    }
    shapes
}

pub fn hydrate_shapes_compact(colors: &[u8], data: &[i16]) -> Vec<Shape> {
    let mut shapes = Vec::new();
    let mut i = 0;
    let mut color_index = 0;
    while i < data.len() {
        let tag = data[i];
        i += 1;
        if tag != 4 || i + 1 >= data.len() || color_index + 2 >= colors.len() {
            break;
        }

        let color = Color::from_u8(
            colors[color_index],
            colors[color_index + 1],
            colors[color_index + 2],
            u8::MAX,
        );
        color_index += 3;
        let start = Vec2::new(f32::from(data[i]) / 100.0, f32::from(data[i + 1]) / 100.0);
        i += 2;

        let mut previous = start;
        let mut commands = vec![PathCommand::MoveTo(start)];

        while i < data.len() && data[i] != 4 {
            let cmd_tag = data[i];
            i += 1;
            match cmd_tag {
                1 => {
                    if i + 1 >= data.len() {
                        break;
                    }
                    let to = Vec2::new(
                        previous.x + f32::from(data[i]) / 100.0,
                        previous.y + f32::from(data[i + 1]) / 100.0,
                    );
                    i += 2;
                    commands.push(PathCommand::LineTo(to));
                    previous = to;
                }
                2 => {
                    if i + 5 >= data.len() {
                        break;
                    }
                    let control1 = Vec2::new(
                        previous.x + f32::from(data[i]) / 100.0,
                        previous.y + f32::from(data[i + 1]) / 100.0,
                    );
                    let control2 = Vec2::new(
                        previous.x + f32::from(data[i + 2]) / 100.0,
                        previous.y + f32::from(data[i + 3]) / 100.0,
                    );
                    let to = Vec2::new(
                        previous.x + f32::from(data[i + 4]) / 100.0,
                        previous.y + f32::from(data[i + 5]) / 100.0,
                    );
                    i += 6;
                    commands.push(PathCommand::CubicTo {
                        control1,
                        control2,
                        to,
                    });
                    previous = to;
                }
                _ => break,
            }
        }

        commands.push(PathCommand::Close);
        shapes.push(Shape {
            variant: ShapeVariant::Path { commands },
            color,
        });
    }
    shapes
}

pub fn hydrate_shapes_compact_indexed(color_indexes: &[u8], data: &[i16]) -> Vec<Shape> {
    let mut shapes = Vec::new();
    let mut i = 0;
    let mut shape_index = 0;
    while i < data.len() {
        let tag = data[i];
        i += 1;
        if tag != 4 || i + 1 >= data.len() || shape_index >= color_indexes.len() {
            break;
        }

        let palette_base = usize::from(color_indexes[shape_index]) * 3;
        shape_index += 1;
        if palette_base + 2 >= SHARED_PALETTE.len() {
            break;
        }

        let color = Color::from_u8(
            SHARED_PALETTE[palette_base],
            SHARED_PALETTE[palette_base + 1],
            SHARED_PALETTE[palette_base + 2],
            u8::MAX,
        );
        let start = Vec2::new(f32::from(data[i]) / 100.0, f32::from(data[i + 1]) / 100.0);
        i += 2;

        let mut previous = start;
        let mut commands = vec![PathCommand::MoveTo(start)];

        while i < data.len() && data[i] != 4 {
            let cmd_tag = data[i];
            i += 1;
            match cmd_tag {
                1 => {
                    if i + 1 >= data.len() {
                        break;
                    }
                    let to = Vec2::new(
                        previous.x + f32::from(data[i]) / 100.0,
                        previous.y + f32::from(data[i + 1]) / 100.0,
                    );
                    i += 2;
                    commands.push(PathCommand::LineTo(to));
                    previous = to;
                }
                2 => {
                    if i + 5 >= data.len() {
                        break;
                    }
                    let control1 = Vec2::new(
                        previous.x + f32::from(data[i]) / 100.0,
                        previous.y + f32::from(data[i + 1]) / 100.0,
                    );
                    let control2 = Vec2::new(
                        previous.x + f32::from(data[i + 2]) / 100.0,
                        previous.y + f32::from(data[i + 3]) / 100.0,
                    );
                    let to = Vec2::new(
                        previous.x + f32::from(data[i + 4]) / 100.0,
                        previous.y + f32::from(data[i + 5]) / 100.0,
                    );
                    i += 6;
                    commands.push(PathCommand::CubicTo {
                        control1,
                        control2,
                        to,
                    });
                    previous = to;
                }
                _ => break,
            }
        }

        commands.push(PathCommand::Close);
        shapes.push(Shape {
            variant: ShapeVariant::Path { commands },
            color,
        });
    }
    shapes
}
