//! Shared hydration function for compact f32-encoded shape data.
//!
//! Auto-generated by img-to-shape — do not edit by hand.

use engine_core::color::Color;
use engine_render::shape::{PathCommand, Shape, ShapeVariant};
use glam::Vec2;

pub fn hydrate_shapes(data: &[f32]) -> Vec<Shape> {
    let mut shapes = Vec::new();
    let mut i = 0;
    while i < data.len() {
        let tag = data[i] as u8;
        i += 1;
        if tag == 4 {
            let color = Color::new(data[i], data[i + 1], data[i + 2], data[i + 3]);
            i += 4;
            let mut commands = Vec::new();
            while i < data.len() && data[i] as u8 != 4 {
                let cmd_tag = data[i] as u8;
                i += 1;
                match cmd_tag {
                    0 => {
                        commands.push(PathCommand::MoveTo(Vec2::new(data[i], data[i + 1])));
                        i += 2;
                    }
                    1 => {
                        commands.push(PathCommand::LineTo(Vec2::new(data[i], data[i + 1])));
                        i += 2;
                    }
                    2 => {
                        commands.push(PathCommand::CubicTo {
                            control1: Vec2::new(data[i], data[i + 1]),
                            control2: Vec2::new(data[i + 2], data[i + 3]),
                            to: Vec2::new(data[i + 4], data[i + 5]),
                        });
                        i += 6;
                    }
                    3 => {
                        commands.push(PathCommand::Close);
                    }
                    _ => break,
                }
            }
            shapes.push(Shape {
                variant: ShapeVariant::Path { commands },
                color,
            });
        }
    }
    shapes
}
