//! Shape repository — caches hydrated art shapes for fast access by name.
//!
//! Auto-generated by img-to-shape — do not edit by hand.

use std::collections::BTreeMap;

use engine_render::shape::Shape;

use super::armor1;

/// Cached shape repository. Call `hydrate_all` once during startup
/// (e.g. splash screen) to populate, then `get` to retrieve cloned shapes.
pub struct ShapeRepository {
    cache: BTreeMap<&'static str, Vec<Shape>>,
}

impl Default for ShapeRepository {
    fn default() -> Self {
        Self::new()
    }
}

impl ShapeRepository {
    pub fn new() -> Self {
        Self {
            cache: BTreeMap::new(),
        }
    }

    /// Hydrate all registered art shapes and store them in the cache.
    pub fn hydrate_all(&mut self) {
        self.cache.insert("armor1", armor1::armor1());
    }

    /// Get a clone of the cached shapes for the given name.
    /// Returns `None` if the name is not in the cache (call `hydrate_all` first).
    pub fn get(&self, name: &str) -> Option<Vec<Shape>> {
        self.cache.get(name).cloned()
    }

    /// Returns the number of cached entries.
    pub fn len(&self) -> usize {
        self.cache.len()
    }

    /// Returns true if the cache is empty.
    pub fn is_empty(&self) -> bool {
        self.cache.is_empty()
    }

    /// Returns an iterator over all cached (name, shapes) pairs.
    pub fn iter(&self) -> impl Iterator<Item = (&&'static str, &Vec<Shape>)> {
        self.cache.iter()
    }
}
