//! Shape repository — caches hydrated art shapes for fast access by name.
//!
//! @generated by img-to-shape — DO NOT EDIT.

use std::collections::BTreeMap;

use bevy_ecs::prelude::Resource;
use engine_render::shape::Shape;

use crate::card::identity::signature::{Aspect, CardSignature, Element};

use super::armor1;
use super::barbarian_icons_01_t;
use super::barbarian_icons_02_t;
use super::barbarian_icons_03_t;
use super::barbarian_icons_04_t;
use super::barbarian_icons_05_t;
use super::barbarian_icons_06_t;

/// A resolved art entry binding a shape list to its card identity metadata.
pub struct ArtEntry {
    shapes: Vec<Shape>,
    element: Element,
    aspect: Aspect,
    signature: CardSignature,
}

impl ArtEntry {
    /// Creates a new `ArtEntry` from a shape list and its card identity metadata.
    pub fn new(
        shapes: Vec<Shape>,
        element: Element,
        aspect: Aspect,
        signature: CardSignature,
    ) -> Self {
        Self {
            shapes,
            element,
            aspect,
            signature,
        }
    }

    /// Returns the element this art entry is associated with.
    pub fn element(&self) -> Element {
        self.element
    }

    /// Returns the aspect this art entry is associated with.
    pub fn aspect(&self) -> Aspect {
        self.aspect
    }

    /// Returns the card signature this art entry is associated with.
    pub fn signature(&self) -> CardSignature {
        self.signature
    }

    /// Returns the shapes for this art entry.
    pub fn shapes(&self) -> &[Shape] {
        &self.shapes
    }
}

/// Cached shape repository. Call `hydrate_all` once during startup
/// (e.g. splash screen) to populate, then `get` to retrieve cloned shapes.
#[derive(Resource)]
pub struct ShapeRepository {
    cache: BTreeMap<&'static str, ArtEntry>,
}

impl Default for ShapeRepository {
    fn default() -> Self {
        Self::new()
    }
}

impl ShapeRepository {
    /// Creates a new empty repository.
    pub fn new() -> Self {
        Self {
            cache: BTreeMap::new(),
        }
    }

    /// Hydrate all registered art shapes and store them in the cache.
    pub fn hydrate_all(&mut self) {
        self.cache.insert(
            "armor1",
            ArtEntry::new(
                armor1::armor1(),
                Element::Solidum,
                Aspect::Solid,
                CardSignature::new([0.14, 0.59, 0.69, -0.92, -0.25, 0.58, 0.93, -0.64]),
            ),
        );
        self.cache.insert(
            "barbarian_icons_01_t",
            ArtEntry::new(
                barbarian_icons_01_t::barbarian_icons_01_t(),
                Element::Solidum,
                Aspect::Solid,
                CardSignature::new([-0.25, -0.38, 0.25, -0.6, -0.49, -0.66, 0.09, 0.53]),
            ),
        );
        self.cache.insert(
            "barbarian_icons_02_t",
            ArtEntry::new(
                barbarian_icons_02_t::barbarian_icons_02_t(),
                Element::Solidum,
                Aspect::Solid,
                CardSignature::new([-0.33, -0.58, 0.45, -0.54, -0.57, -0.86, 0.3, 0.58]),
            ),
        );
        self.cache.insert(
            "barbarian_icons_03_t",
            ArtEntry::new(
                barbarian_icons_03_t::barbarian_icons_03_t(),
                Element::Solidum,
                Aspect::Solid,
                CardSignature::new([-0.38, -0.52, 0.37, -0.45, -0.63, -0.81, 0.24, 0.65]),
            ),
        );
        self.cache.insert(
            "barbarian_icons_04_t",
            ArtEntry::new(
                barbarian_icons_04_t::barbarian_icons_04_t(),
                Element::Solidum,
                Aspect::Solid,
                CardSignature::new([0.09, -0.72, 0.59, -0.94, -0.69, -0.47, -0.1, 0.73]),
            ),
        );
        self.cache.insert(
            "barbarian_icons_05_t",
            ArtEntry::new(
                barbarian_icons_05_t::barbarian_icons_05_t(),
                Element::Solidum,
                Aspect::Solid,
                CardSignature::new([0.01, -0.64, 0.5, -0.88, -0.78, -0.4, -0.16, 0.78]),
            ),
        );
        self.cache.insert(
            "barbarian_icons_06_t",
            ArtEntry::new(
                barbarian_icons_06_t::barbarian_icons_06_t(),
                Element::Solidum,
                Aspect::Solid,
                CardSignature::new([-0.04, -0.86, 0.71, -0.79, -0.83, -0.61, 0.04, 0.86]),
            ),
        );
    }

    /// Get a clone of the cached shapes for the given name.
    /// Returns `None` if the name is not in the cache (call `hydrate_all` first).
    pub fn get(&self, name: &str) -> Option<Vec<Shape>> {
        self.cache.get(name).map(|entry| entry.shapes.clone())
    }

    /// Get a reference to the full art entry for the given name.
    /// Returns `None` if the name is not in the cache (call `hydrate_all` first).
    pub fn get_entry(&self, name: &str) -> Option<&ArtEntry> {
        self.cache.get(name)
    }

    /// Insert an art entry into the cache.
    pub fn insert(&mut self, name: &'static str, entry: ArtEntry) {
        self.cache.insert(name, entry);
    }

    /// Returns all entries matching the given element.
    pub fn by_element(&self, element: Element) -> Vec<(&str, &ArtEntry)> {
        self.cache
            .iter()
            .filter(|(_, entry)| entry.element == element)
            .map(|(&name, entry)| (name, entry))
            .collect()
    }

    /// Returns all entries matching the given aspect.
    pub fn by_aspect(&self, aspect: Aspect) -> Vec<(&str, &ArtEntry)> {
        self.cache
            .iter()
            .filter(|(_, entry)| entry.aspect == aspect)
            .map(|(&name, entry)| (name, entry))
            .collect()
    }

    /// Returns the `n` entries closest to the given signature, sorted by distance ascending.
    pub fn closest_to(&self, query: &CardSignature, n: usize) -> Vec<(&str, &ArtEntry)> {
        let mut entries: Vec<(&str, &ArtEntry, f32)> = self
            .cache
            .iter()
            .map(|(&name, entry)| (name, entry, entry.signature.distance_to(query)))
            .collect();
        entries.sort_by(|a, b| a.2.partial_cmp(&b.2).unwrap_or(std::cmp::Ordering::Equal));
        entries
            .into_iter()
            .take(n)
            .map(|(name, entry, _)| (name, entry))
            .collect()
    }

    /// Returns the number of cached entries.
    pub fn len(&self) -> usize {
        self.cache.len()
    }

    /// Returns true if the cache is empty.
    pub fn is_empty(&self) -> bool {
        self.cache.is_empty()
    }

    /// Returns an iterator over all cached (name, entry) pairs.
    pub fn iter(&self) -> impl Iterator<Item = (&&'static str, &ArtEntry)> {
        self.cache.iter()
    }
}
