//! Art selection, fitting, and bounding-box utilities.
//!
//! Hand-maintained — NOT generated by img-to-shape.

use engine_render::shape::{ColorVertex, TessellatedColorMesh};

use crate::card::art::repository::{ArtEntry, ShapeRepository};
use crate::card::identity::signature::{CardSignature, Element};

/// Returns the first art entry whose element matches the dominant axis of `signature`.
///
/// Falls back to the closest entry by signature distance if no element match exists.
/// Returns `None` if the repository is empty.
pub fn select_art_for_signature<'a>(
    signature: &CardSignature,
    repo: &'a ShapeRepository,
) -> Option<&'a ArtEntry> {
    let dominant = Element::ALL.iter().copied().max_by(|&a, &b| {
        signature
            .intensity(a)
            .partial_cmp(&signature.intensity(b))
            .unwrap_or(std::cmp::Ordering::Equal)
    })?;
    repo.by_element(dominant)
        .into_iter()
        .next()
        .map(|(_, e)| e)
        .or_else(|| {
            repo.closest_to(signature, 1)
                .into_iter()
                .next()
                .map(|(_, e)| e)
        })
}

/// Returns the axis-aligned bounding box `(min, max)` of the mesh, or `None` if empty.
pub fn art_bounding_box(mesh: &TessellatedColorMesh) -> Option<([f32; 2], [f32; 2])> {
    let first = mesh.vertices.first()?;
    let mut min = first.position;
    let mut max = first.position;
    for v in &mesh.vertices[1..] {
        min[0] = min[0].min(v.position[0]);
        min[1] = min[1].min(v.position[1]);
        max[0] = max[0].max(v.position[0]);
        max[1] = max[1].max(v.position[1]);
    }
    Some((min, max))
}

/// Uniformly scales and centers a mesh to fit within `region_half_w × region_half_h`
/// centered at `(0, region_center_y)`. Returns an empty mesh if the input is empty.
pub fn fit_art_mesh_to_region(
    mesh: &TessellatedColorMesh,
    region_half_w: f32,
    region_half_h: f32,
    region_center_y: f32,
) -> TessellatedColorMesh {
    let Some((min, max)) = art_bounding_box(mesh) else {
        return TessellatedColorMesh::new();
    };

    let art_w = max[0] - min[0];
    let art_h = max[1] - min[1];
    if art_w == 0.0 || art_h == 0.0 {
        return TessellatedColorMesh::new();
    }

    let scale = (region_half_w * 2.0 / art_w).min(region_half_h * 2.0 / art_h);
    let centroid_x = f32::midpoint(min[0], max[0]);
    let centroid_y = f32::midpoint(min[1], max[1]);

    let vertices = mesh
        .vertices
        .iter()
        .map(|v| ColorVertex {
            position: [
                (v.position[0] - centroid_x) * scale,
                (v.position[1] - centroid_y) * scale + region_center_y,
            ],
            color: v.color,
            uv: v.uv,
        })
        .collect();

    TessellatedColorMesh {
        vertices,
        indices: mesh.indices.clone(),
    }
}
