// EVOLVE-BLOCK-START
//! Art selection, fitting, and bounding-box utilities.
//!
//! Hand-maintained — NOT generated by img-to-shape.

use rand::SeedableRng;
use rand_chacha::ChaCha8Rng;

use engine_render::shape::{ColorVertex, TessellatedColorMesh};

use crate::card::art::repository::{ArtEntry, ShapeRepository};
use crate::card::identity::signature::CardSignature;

/// Gaussian sigma for art selection weight falloff.
///
/// Controls how sharply probability decays with signature distance.
/// Tuned so that at distance 0 (exact match) the closest art gets ~20–30%
/// of the probability mass with ~361 entries, yielding ~2–3 matching cards
/// in a typical 10-card booster.
///
/// Smaller → more deterministic (closest wins). Larger → more uniform.
const SELECTION_SIGMA: f32 = 0.8;

/// Selects an art entry using signature-seeded Gaussian-weighted sampling.
///
/// Each card signature deterministically seeds an RNG, then samples from
/// a probability distribution where weight = exp(-d²/(2σ²)). This produces
/// a "blue-noise dithered soft Voronoi" — the closest art entry is most likely,
/// but even at distance 0 the match probability is only ~25%, and neighboring
/// signatures diverge chaotically due to the hash-seeded RNG.
pub fn select_art_for_signature<'a>(
    signature: &CardSignature,
    repo: &'a ShapeRepository,
) -> Option<&'a ArtEntry> {
    if repo.is_empty() {
        return None;
    }

    // Seed RNG deterministically from the 32 raw signature bytes (8 × f32).
    // Identical signatures always produce the same art pick; even a 1-ULP
    // change in any axis produces a completely different ChaCha stream.
    let axes = signature.axes();
    let mut seed = [0u8; 32];
    for (i, &v) in axes.iter().enumerate() {
        seed[i * 4..(i + 1) * 4].copy_from_slice(&v.to_le_bytes());
    }
    let mut rng = ChaCha8Rng::from_seed(seed);

    // Compute Gaussian weights for every entry in the repository.
    let two_sigma_sq = f64::from(2.0_f32 * SELECTION_SIGMA * SELECTION_SIGMA);
    let mut total_weight = 0.0_f64;
    let mut entries: Vec<(&ArtEntry, f64)> = Vec::with_capacity(repo.len());

    for (_, entry) in repo.iter() {
        let dist = f64::from(entry.signature().distance_to(signature));
        let weight = (-dist * dist / two_sigma_sq).exp();
        total_weight += weight;
        entries.push((entry, weight));
    }

    if total_weight < f64::EPSILON {
        // All weights negligible — fall back to nearest entry.
        return repo
            .closest_to(signature, 1)
            .into_iter()
            .next()
            .map(|(_, e)| e);
    }

    // Weighted random sample using the signature-seeded RNG.
    let threshold: f64 = rand::Rng::random_range(&mut rng, 0.0_f64..1.0_f64) * total_weight;
    let mut cumulative = 0.0_f64;
    for &(entry, weight) in &entries {
        cumulative += weight;
        if cumulative >= threshold {
            return Some(entry);
        }
    }

    // Float precision fallback.
    entries.last().map(|(entry, _)| *entry)
}

/// Returns the axis-aligned bounding box `(min, max)` of the mesh, or `None` if empty.
pub fn art_bounding_box(mesh: &TessellatedColorMesh) -> Option<([f32; 2], [f32; 2])> {
    let first = mesh.vertices.first()?;
    let mut min = first.position;
    let mut max = first.position;
    for v in &mesh.vertices[1..] {
        min[0] = min[0].min(v.position[0]);
        min[1] = min[1].min(v.position[1]);
        max[0] = max[0].max(v.position[0]);
        max[1] = max[1].max(v.position[1]);
    }
    Some((min, max))
}

/// Uniformly scales and centers a mesh to fit within `region_half_w × region_half_h`
/// centered at `(0, region_center_y)`. Returns an empty mesh if the input is empty.
pub fn fit_art_mesh_to_region(
    mesh: &TessellatedColorMesh,
    region_half_w: f32,
    region_half_h: f32,
    region_center_y: f32,
) -> TessellatedColorMesh {
    let Some((min, max)) = art_bounding_box(mesh) else {
        return TessellatedColorMesh::new();
    };

    let art_w = max[0] - min[0];
    let art_h = max[1] - min[1];
    if art_w == 0.0 || art_h == 0.0 {
        return TessellatedColorMesh::new();
    }

    let scale = (region_half_w * 2.0 / art_w).min(region_half_h * 2.0 / art_h);
    let centroid_x = f32::midpoint(min[0], max[0]);
    let centroid_y = f32::midpoint(min[1], max[1]);

    let vertices = mesh
        .vertices
        .iter()
        .map(|v| ColorVertex {
            position: [
                (v.position[0] - centroid_x) * scale,
                (v.position[1] - centroid_y) * scale + region_center_y,
            ],
            color: v.color,
            uv: v.uv,
        })
        .collect();

    TessellatedColorMesh {
        vertices,
        indices: mesh.indices.clone(),
    }
}
// EVOLVE-BLOCK-END
